services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: unless-stopped
    build:
     context: .
     dockerfile: ./postgres/Dockerfile.postgres
    environment:
      POSTGRES_DB: 'sample'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_password'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "9999:5432"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    stdin_open: true
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules      
    ports:
      - "3000:3000"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env 

  gateway:
    container_name: gateway
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3200:3200"
    volumes:
      - ./monitoring_stack/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_PORT=3200
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
      - loki
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring_stack/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    build:
      context: .
      dockerfile: ./monitoring_stack/loki/Dockerfile
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring_stack/loki/loki-config.yml:/etc/loki/config.yml
      - ./monitoring_stack/loki/loki_data:/loki    
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    ports:
      - "9273:9273"
    depends_on:
      - prometheus
    user: "1000:999" # Adjust UID:GID according to environment, using 'id' command
    volumes:
      - ./monitoring_stack/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/host:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - /dev:/host/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_ETC=/host/etc
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_RUN=/host/run
      - HOST_DEV=/host/dev
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  log_pusher:
    build: 
      context: ./monitoring_stack/log_pusher
      dockerfile: Dockerfile
    container_name: log_pusher
    restart: unless-stopped
    user: "1000:999" # Adjust UID:GID according to environment, using 'id' command
    group_add:
      - adm
    command: python3 push_logs.py
    volumes:
      - ./monitoring_stack/log_pusher/push_logs.py:/app/push_logs.py:ro
      - ./monitoring_stack/log_pusher/offsets:/app/state
      - ./geoip_db/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb:ro # add manually your own copy due to the copyright
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/dpkg.log:/var/log/dpkg.log:ro
      - /var/log/fail2ban.log:/var/log/fail2ban.log:ro
      - ${HOME}/gateway_logs.log:/host_home/gateway_logs.log:ro
      #- ${HOME}/geoip2_lite.log:/host_home/geoip2_lite.log:ro # not implemented in this demo
      #- ${HOME}/cookie_consent.log:/host_home/cookie_consent.log:ro # not implemented in this demo
    #environment:
    #  - FILTERED_IP=${FILTERED_IP} # if specified in .env, filters out a certain IP address from gateway nad fail2ban logs
    depends_on:
      - loki
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  process_exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process_exporter
    restart: unless-stopped
    ports:
      - "9256:9256"
    depends_on:
      - prometheus
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - ./monitoring_stack/process_exporter_config.yml:/etc/process-exporter/config.yml:ro
    command:
      - "--procfs=/host/proc"
      - "--config.path=/etc/process-exporter/config.yml"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    ports:
      - "9187:9187"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
  prometheus_data:
  grafana_data:

networks:
  my-network:
    driver: bridge
    name: ubuntu_my-network